### ISSUE TITLE
Exploring the Feasibility of Expanding GBA Memory

### ISSUE THREAD

**Issue by panzoe** [HorstBaerbel/GBA-mem#2]
Hello,

I came across this project and I'm genuinely impressed by its capabilities. However, it seems the project primarily focuses on achieving higher memory frequencies. I'd like to inquire whether it's possible to expand the memory capacity of the GBA. The current memory size is quite restrictive, especially when it comes to creating custom programs for the GBA.

Is it feasible to consider replacing the existing eWRAM chip or even introducing an additional eWRAM-like chip into the circuit to provide more memory for program utilization? For instance, is there a way to increase the memory to 64/128/256/512MB?

**Comment by HorstBaerbel** [comment]
Hi panzoe. 
The GBA CPU only has enough address lines for addressing 256kB of external memory / EWRAM. Switching memory chips / address lanes is not a good idea due random memory accesses being impossible and afaik the stack being in EWRAM too. So, no I guess.
That said 256kB EWRAM + 32kB IWRAM + 96kB VRAM is a good amount of memory for such a system. If that's not enough for you, you're probably "doing it wrong". On limited systems you have to get creative, cut corners, pre-process as much as you can.
